'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ManagementForm
    
    '''<summary>
    '''dvMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvMain As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''tbMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbMain As Global.Telerik.Web.UI.RadToolBar
    
    '''<summary>
    '''upnMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upnMain As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''dvUpdateMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvUpdateMain As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lbPlant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbPlant As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddPlantGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddPlantGroup As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''lbProvince control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbProvince As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddProvince control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddProvince As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''lbAmphoe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbAmphoe As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddAmphoe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddAmphoe As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''lbTambon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbTambon As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddTambon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddTambon As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''lbFarmer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbFarmer As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtFarmer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFarmer As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''lbArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbArea As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtArea As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''lbStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbStartDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dpStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dpStartDate As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''lbEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbEndDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dpEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dpEndDate As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''rqdpEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rqdpEndDate As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lbSuite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSuite As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtSuite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSuite As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''lbWater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbWater As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtWater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWater As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''lbDemand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDemand As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtDemand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDemand As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''lbScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbScore As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScore As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''lbForecast control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbForecast As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbReal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbReal As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbCost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCost As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtForecastCost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtForecastCost As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''txtRealCost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRealCost As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''lbProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbProduct As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtForecastProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtForecastProduct As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''txtRealProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRealProduct As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''rqtxtRealProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rqtxtRealProduct As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lbPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbPrice As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtForecastPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtForecastPrice As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''txtRealPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRealPrice As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''rqtxtRealPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rqtxtRealPrice As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lbProfit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbProfit As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtForecastProfit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtForecastProfit As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''txtRealProfit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRealProfit As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''rqtxtRealProfit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rqtxtRealProfit As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lbComplete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbComplete As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbCompleted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbCompleted As Global.Telerik.Web.UI.RadCheckBox
    
    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''btnBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBack As Global.Telerik.Web.UI.RadButton
End Class
