'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Suggestion
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''RadScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptManager1 As Global.Telerik.Web.UI.RadScriptManager
    
    '''<summary>
    '''sb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sb As Global.Telerik.Web.UI.RadScriptBlock
    
    '''<summary>
    '''mnuMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuMain As Global.Telerik.Web.UI.RadMenu
    
    '''<summary>
    '''updateProgress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updateProgress As Global.System.Web.UI.UpdateProgress
    
    '''<summary>
    '''upnHead control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upnHead As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''dvHead control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvHead As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddProvince control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddProvince As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''ddAmphoe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddAmphoe As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''ddTambon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddTambon As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''namePlace control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents namePlace As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''url control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents url As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''criteria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents criteria As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''lbllatitude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbllatitude As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtlat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtlat As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''lat_value control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lat_value As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''lblongtitude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblongtitude As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtlon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtlon As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''lon_value control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lon_value As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''lbarea_desc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbarea_desc As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbsoil_desc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbsoil_desc As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbdrainage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbdrainage As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblimitation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblimitation As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbslope control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbslope As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbt1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbt1 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbt2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbt2 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbt3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbt3 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbt4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbt4 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbt5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbt5 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbt6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbt6 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbt7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbt7 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbt8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbt8 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbt9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbt9 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbt10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbt10 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''txtCrop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCrop As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''rqtxtCrop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rqtxtCrop As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''dpStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dpStart As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''rpdpStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpdpStart As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''pbAdvance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pbAdvance As Global.Telerik.Web.UI.RadPanelBar
    
    '''<summary>
    '''hdSuitWeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdSuitWeight As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdWaterWeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdWaterWeight As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdProfitWeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdProfitWeight As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdDemandWeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdDemandWeight As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdRiceCost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdRiceCost As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdCornCost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdCornCost As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdCaneCost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdCaneCost As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdCassavaCost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdCassavaCost As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdRiceYield control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdRiceYield As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdCornYield control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdCornYield As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdCaneYield control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdCaneYield As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdCassavaYield control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdCassavaYield As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdRiceCrop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdRiceCrop As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdCornCrop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdCornCrop As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdCaneCrop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdCaneCrop As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdCassavaCrop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdCassavaCrop As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''btnView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnView As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''lbRiceSuit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbRiceSuit As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbCornSuit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCornSuit As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbCaneSuit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCaneSuit As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbCassavaSuit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCassavaSuit As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbRiceWater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbRiceWater As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbCornWater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCornWater As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbCaneWater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCaneWater As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbCassavaWater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCassavaWater As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbRiceCrop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbRiceCrop As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbCornCrop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCornCrop As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbCaneCrop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCaneCrop As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbCassavaCrop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCassavaCrop As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbRiceDemand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbRiceDemand As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbCornDemand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCornDemand As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbCaneDemand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCaneDemand As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbCassavaDemand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCassavaDemand As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbRiceRemain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbRiceRemain As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbCornRemain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCornRemain As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbCaneRemain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCaneRemain As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbCassavaRemain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCassavaRemain As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbRiceYield control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbRiceYield As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbCornYield control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCornYield As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbCaneYield control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCaneYield As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbCassavaYield control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCassavaYield As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbRiceCost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbRiceCost As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbCornCost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCornCost As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbCaneCost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCaneCost As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbCassavaCost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCassavaCost As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbRicePrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbRicePrice As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbCornPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCornPrice As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbCanePrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCanePrice As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbCassavaPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCassavaPrice As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbRiceProfit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbRiceProfit As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbCornProfit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCornProfit As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbCaneProfit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCaneProfit As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbCassavaProfit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCassavaProfit As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbRiceScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbRiceScore As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbCornScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCornScore As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbCaneScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCaneScore As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbCassavaScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCassavaScore As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtFarmer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFarmer As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''ddPlantGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddPlantGroup As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''btnChoosed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnChoosed As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''bc1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bc1 As Global.Telerik.Web.UI.RadHtmlChart
    
    '''<summary>
    '''bc2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bc2 As Global.Telerik.Web.UI.RadHtmlChart
    
    '''<summary>
    '''bc3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bc3 As Global.Telerik.Web.UI.RadHtmlChart
    
    '''<summary>
    '''bc4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bc4 As Global.Telerik.Web.UI.RadHtmlChart
    
    '''<summary>
    '''bc5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bc5 As Global.Telerik.Web.UI.RadHtmlChart
    
    '''<summary>
    '''bc6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bc6 As Global.Telerik.Web.UI.RadHtmlChart
    
    '''<summary>
    '''bc7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bc7 As Global.Telerik.Web.UI.RadHtmlChart
    
    '''<summary>
    '''bc8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bc8 As Global.Telerik.Web.UI.RadHtmlChart
    
    '''<summary>
    '''bc9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bc9 As Global.Telerik.Web.UI.RadHtmlChart
    
    '''<summary>
    '''bc10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bc10 As Global.Telerik.Web.UI.RadHtmlChart
End Class
